-- =============================================================================
-- schema.sql
-- Meridian Systems corporate website — database schema (PostgreSQL)
-- Import this file into PostgreSQL 16+ before uploading the application.
--   psql -h your_host -U your_user -d your_database -f schema.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: clients
-- Stores client portal login credentials. Passwords are always stored as
-- bcrypt hashes generated by PHP's password_hash() — never plain text.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clients (
    id            SERIAL PRIMARY KEY,
    client_id     VARCHAR(64)  NOT NULL UNIQUE,
    company_name  VARCHAR(150) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Table: feedback
-- Feedback entries linked to a client, with a sentiment classification used
-- to power the dashboard's statistics and charts.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feedback (
    id          SERIAL PRIMARY KEY,
    client_id   VARCHAR(64) NOT NULL,
    feedback    TEXT        NOT NULL,
    sentiment   VARCHAR(20) NOT NULL DEFAULT 'neutral' CHECK (sentiment IN ('positive', 'negative', 'neutral')),
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feedback_client ON feedback(client_id);
CREATE INDEX IF NOT EXISTS idx_feedback_created ON feedback(created_at);

ALTER TABLE feedback 
    ADD CONSTRAINT fk_feedback_client 
    FOREIGN KEY (client_id) REFERENCES clients(client_id)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- -----------------------------------------------------------------------------
-- Table: contact_messages
-- Submissions from the public Contact Us form.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    phone       VARCHAR(20),
    company     VARCHAR(150),
    message     TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contact_created ON contact_messages(created_at);

-- -----------------------------------------------------------------------------
-- Seed data: one sample client so the portal is immediately testable.
--
--   Client ID:  democlient
--   Password:   Demo@12345
--
-- The hash below is a genuine bcrypt hash of 'Demo@12345' (cost factor 10),
-- fully compatible with PHP's password_verify(). Replace this account (or
-- its password) before going to production.
-- -----------------------------------------------------------------------------
INSERT INTO clients (client_id, company_name, password) VALUES
('democlient', 'Demo Client Co.', '$2b$10$sQsC3Mu3ApwPZXaJBgReqejvtQGW0DAdTaBr91FvOa.4Cw0UlKVTe')
ON CONFLICT (client_id) DO NOTHING;

-- Sample feedback rows so the dashboard charts render meaningful data
-- immediately after import.
INSERT INTO feedback (client_id, feedback, sentiment, created_at) VALUES
('democlient', 'The new dashboard is much clearer than before.', 'positive', NOW() - INTERVAL '1 DAY'),
('democlient', 'Loved how fast the support team responded.', 'positive', NOW() - INTERVAL '2 DAY'),
('democlient', 'Chart loading felt slow on my last visit.', 'negative', NOW() - INTERVAL '3 DAY'),
('democlient', 'Great onboarding experience overall.', 'positive', NOW() - INTERVAL '4 DAY'),
('democlient', 'Would like a dark mode option.', 'neutral', NOW() - INTERVAL '5 DAY'),
('democlient', 'Login page occasionally times out too fast.', 'negative', NOW() - INTERVAL '6 DAY'),
('democlient', 'The AI assistant answered my question quickly.', 'positive', NOW() - INTERVAL '7 DAY');
