-- =============================================================================
-- schema.sql
-- Meridian Systems corporate website — database schema
-- Import this file into MySQL 8+ before uploading the application.
--   mysql -u your_user -p your_database < schema.sql
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------------------------------
-- Table: clients
-- Stores client portal login credentials. Passwords are always stored as
-- bcrypt hashes generated by PHP's password_hash() — never plain text.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clients (
    id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    client_id     VARCHAR(64)  NOT NULL UNIQUE,
    company_name  VARCHAR(150) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- Table: feedback
-- Feedback entries linked to a client, with a sentiment classification used
-- to power the dashboard's statistics and charts.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feedback (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    client_id   VARCHAR(64) NOT NULL,
    feedback    TEXT        NOT NULL,
    sentiment   ENUM('positive', 'negative', 'neutral') NOT NULL DEFAULT 'neutral',
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_feedback_client (client_id),
    INDEX idx_feedback_created (created_at),
    CONSTRAINT fk_feedback_client
        FOREIGN KEY (client_id) REFERENCES clients(client_id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- Table: contact_messages
-- Submissions from the public Contact Us form.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    phone       VARCHAR(20)  NULL,
    company     VARCHAR(150) NULL,
    message     TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_contact_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- -----------------------------------------------------------------------------
-- Seed data: one sample client so the portal is immediately testable.
--
--   Client ID:  democlient
--   Password:   Demo@12345
--
-- The hash below is a genuine bcrypt hash of 'Demo@12345' (cost factor 10),
-- fully compatible with PHP's password_verify(). Replace this account (or
-- its password) before going to production.
-- -----------------------------------------------------------------------------
INSERT INTO clients (client_id, company_name, password) VALUES
('democlient', 'Demo Client Co.', '$2b$10$sQsC3Mu3ApwPZXaJBgReqejvtQGW0DAdTaBr91FvOa.4Cw0UlKVTe')
ON DUPLICATE KEY UPDATE client_id = client_id;

-- Sample feedback rows so the dashboard charts render meaningful data
-- immediately after import.
INSERT INTO feedback (client_id, feedback, sentiment, created_at) VALUES
('democlient', 'The new dashboard is much clearer than before.', 'positive', NOW() - INTERVAL 1 DAY),
('democlient', 'Loved how fast the support team responded.', 'positive', NOW() - INTERVAL 2 DAY),
('democlient', 'Chart loading felt slow on my last visit.', 'negative', NOW() - INTERVAL 3 DAY),
('democlient', 'Great onboarding experience overall.', 'positive', NOW() - INTERVAL 4 DAY),
('democlient', 'Would like a dark mode option.', 'neutral', NOW() - INTERVAL 5 DAY),
('democlient', 'Login page occasionally times out too fast.', 'negative', NOW() - INTERVAL 6 DAY),
('democlient', 'The AI assistant answered my question quickly.', 'positive', NOW() - INTERVAL 7 DAY);
